from __future__ import annotations

from .models import DashboardSpec, TileSpec


def default_dashboard_spec(dashboard_id: str = "kalshi_autonomous_v1") -> DashboardSpec:
    return DashboardSpec(
        dashboard_id=dashboard_id,
        version=3,
        title="Kalshi Autonomous Control Center",
        description="Role-based, spec-driven dashboard rendered by React and updated by agent proposals.",
        refresh_seconds=60,
        tiles=[
            TileSpec(
                tile_id="pipeline_heartbeat",
                title="Pipeline Heartbeat",
                description="Freshness, quality failures, and hourly API activity.",
                view_name="vw_pipeline_heartbeat",
                viz_type="scorecard",
                columns=[
                    "minutes_since_latest_market_snapshot",
                    "minutes_since_latest_trade",
                    "minutes_since_latest_orderbook_level",
                    "quality_failures_last_60m",
                    "api_calls_last_60m",
                ],
                default_limit=1,
                roles=["de"],
            ),
            TileSpec(
                tile_id="quality_checks_24h",
                title="Quality Checks (24h)",
                description="Gate checks from autonomous pipeline runs.",
                view_name="vw_quality_checks_24h",
                viz_type="table",
                columns=[
                    "checked_at",
                    "run_id",
                    "check_name",
                    "status",
                    "metric_value",
                    "threshold_value",
                ],
                order_by="checked_at",
                order_dir="desc",
                default_limit=150,
                roles=["de"],
            ),
            TileSpec(
                tile_id="ingestion_throughput_24h",
                title="Ingestion Throughput (24h)",
                description="API call rate by endpoint and minute.",
                view_name="vw_ingestion_throughput_24h",
                viz_type="timeseries",
                columns=[
                    "ts_minute",
                    "endpoint",
                    "api_call_count",
                ],
                order_by="ts_minute",
                order_dir="desc",
                default_limit=500,
                roles=["de"],
            ),
            TileSpec(
                tile_id="endpoint_gap_24h",
                title="Endpoint Gap (24h)",
                description="Average seconds between API pulls, by endpoint.",
                view_name="vw_endpoint_gap_24h",
                viz_type="timeseries",
                columns=["ts_minute", "endpoint", "avg_gap_seconds", "samples"],
                order_by="ts_minute",
                order_dir="desc",
                default_limit=500,
                roles=["de"],
            ),
            TileSpec(
                tile_id="kpi_trend_24h",
                title="KPI Trend (24h)",
                description="Volume, open interest, and trade lookback on 5m buckets.",
                view_name="vw_kpi_5m_24h",
                viz_type="timeseries",
                columns=[
                    "kpi_ts",
                    "series_ticker",
                    "total_volume_dollars",
                    "total_open_interest_dollars",
                    "trade_count_lookback",
                ],
                order_by="kpi_ts",
                order_dir="desc",
                default_limit=300,
                roles=["analyst"],
            ),
            TileSpec(
                tile_id="event_activity_24h",
                title="Event Activity (24h)",
                description="Trade concentration by event, not just market ticker.",
                view_name="vw_event_activity_24h",
                viz_type="table",
                columns=[
                    "event_title",
                    "event_sub_title",
                    "trade_count_24h",
                    "contracts_traded_24h",
                    "market_count_24h",
                    "last_trade_ts",
                ],
                order_by="contracts_traded_24h",
                order_dir="desc",
                default_limit=35,
                roles=["analyst"],
            ),
            TileSpec(
                tile_id="top_markets_60m",
                title="Most Traded Markets (60m)",
                description="Top markets by contract flow, with event context.",
                view_name="vw_most_traded_markets_60m",
                viz_type="table",
                columns=[
                    "event_title",
                    "event_sub_title",
                    "market_ticker",
                    "trade_count",
                    "contracts_traded",
                    "avg_yes_price_dollars",
                    "last_trade_ts",
                ],
                order_by="contracts_traded",
                order_dir="desc",
                default_limit=25,
                roles=["analyst"],
            ),
            TileSpec(
                tile_id="trade_flow_6h",
                title="Trade Flow by Side (6h)",
                description="Trade count and contracts by minute and taker side.",
                view_name="vw_trade_flow_6h",
                viz_type="timeseries",
                columns=["ts_minute", "taker_side", "trade_count", "contracts_traded"],
                order_by="ts_minute",
                order_dir="desc",
                default_limit=500,
                roles=["analyst"],
            ),
            TileSpec(
                tile_id="price_movers_60m",
                title="Price Movers (60m)",
                description="Largest YES price moves by market and event.",
                view_name="vw_price_movers_60m",
                viz_type="table",
                columns=[
                    "event_title",
                    "event_sub_title",
                    "market_ticker",
                    "first_yes_price",
                    "last_yes_price",
                    "abs_move",
                    "pct_move",
                    "last_ts",
                ],
                order_by="abs_move",
                order_dir="desc",
                default_limit=30,
                roles=["analyst"],
            ),
            TileSpec(
                tile_id="ds_feature_drift_24h",
                title="Feature Drift (Last 6h vs Prev 6h)",
                description="Market-level drift in YES price and contract flow.",
                view_name="vw_ds_feature_drift_24h",
                viz_type="table",
                columns=[
                    "market_ticker",
                    "trades_last_6h",
                    "trades_prev_6h",
                    "mean_yes_price_last_6h",
                    "mean_yes_price_prev_6h",
                    "yes_price_pct_shift",
                    "contracts_pct_shift",
                ],
                order_by="yes_price_pct_shift",
                order_dir="desc",
                default_limit=50,
                roles=["ds"],
            ),
            TileSpec(
                tile_id="ds_label_coverage_24h",
                title="Training Readiness (24h)",
                description="Coverage checks for model features and labels.",
                view_name="vw_ds_label_coverage_24h",
                viz_type="scorecard",
                columns=[
                    "total_trades_24h",
                    "active_markets_24h",
                    "yes_price_coverage_ratio",
                    "contracts_coverage_ratio",
                    "non_null_taker_side_ratio",
                ],
                default_limit=1,
                roles=["ds"],
            ),
            TileSpec(
                tile_id="ds_retrain_signal_24h",
                title="Retrain Priority Markets (24h)",
                description="Markets ranked by volatility-volume composite score.",
                view_name="vw_ds_retrain_signal_24h",
                viz_type="table",
                columns=[
                    "market_ticker",
                    "trade_count_24h",
                    "contracts_traded_24h",
                    "yes_price_mean",
                    "yes_price_stddev",
                    "retrain_priority_score",
                ],
                order_by="retrain_priority_score",
                order_dir="desc",
                default_limit=40,
                roles=["ds"],
            ),
        ],
    )
